pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK21'
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build + UI/API Testing') {
            steps {
                dir('Mix_up') {
                    bat 'mvn clean test'
                }
            }
        }

        stage('JMeter Performance Test') {
            steps {
                dir('Mix_up') {
                    bat 'jmeter -n -t src/test/resources/jmeter/testplan.jmx -l results.jtl'
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                allure([
                    includeProperties: false,
                    jdk: '',
                    results: [[path: 'Mix_up/allure-results']]
                ])
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}
